#!/usr/bin/env python

import os, sys, re
import argparse
import subprocess

HOMEDIR=os.path.dirname(os.path.realpath(__file__))
MAKEFILE=os.path.join(HOMEDIR,"main.mk")


parser = argparse.ArgumentParser(description='Generate NICE PDFs from Confluence exports.')

parser.add_argument('filename', metavar='FILE', nargs=1, help='Confluence HTML export zipfile')

args = parser.parse_args()

if args.filename:
    subprocess.call(["make", "SPACE="+args.filename[0]])
else:
    print "I kind of need a filename, thanks"
    sys.exit()
